# Generated by Django 5.2 on 2025-04-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.AddField(
            model_name="customuser",
            name="money",
            field=models.FloatField(default=10.0),
        ),
    ]
