# Generated by Django 5.2 on 2025-04-22 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pot", models.FloatField(default=0.0)),
                ("current_bet", models.FloatField(default=0.0)),
                ("small_blind", models.FloatField(default=0.1)),
                ("big_blind", models.FloatField(default=0.25)),
                ("winner_determined", models.BooleanField(default=False)),
                ("dealer_seat_index", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cards", models.JSONField(blank=True, default=list)),
                ("community_cards", models.JSONField(blank=True, default=list)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck",
                        to="gameplay.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet_amount", models.FloatField(default=0.0)),
                ("last_bet", models.FloatField(default=0.0)),
                ("beginning_money", models.FloatField(default=0.0)),
                ("all_in_pot_amount", models.FloatField(default=0.0)),
                ("all_in_difference", models.FloatField(default=0.0)),
                ("hand", models.JSONField(blank=True, default=list)),
                ("seat_position", models.PositiveIntegerField(default=0)),
                ("sitting_in", models.BooleanField(default=False)),
                ("is_folded", models.BooleanField(default=False)),
                ("is_all_in", models.BooleanField(default=False)),
                ("is_dealer", models.BooleanField(default=False)),
                ("is_small_blind", models.BooleanField(default=False)),
                ("is_big_blind", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="gameplay.player"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.ManyToManyField(blank=True, to="gameplay.player"),
        ),
    ]
