# Generated by Django 5.2 on 2025-04-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_active",
            field=models.BooleanField(default=True),
        ),
    ]
